const Assets = {
  // Illustrations
  billetes: require('~/assets/images/ilustrations/Billetes.webp'),
  bombilla: require('~/assets/images/ilustrations/Bombilla.webp'),
  cajaFuerte: require('~/assets/images/ilustrations/CajaFuerte.webp'),
  campanaDinamica: require('~/assets/images/ilustrations/bell-dynamic-color.svg'),
  candandoBien: require('~/assets/images/ilustrations/Candado Bien.webp'),
  candadoMal: require('~/assets/images/ilustrations/Candado Mal.webp'),
  cartera: require('~/assets/images/ilustrations/Cartera.webp'),
  cloud: require('~/assets/images/ilustrations/cloudcomputing_error500.webp'),
  cohete: require('~/assets/images/ilustrations/Cohete.webp'),
  comentarioAmor: require('~/assets/images/ilustrations/ComentarioAmor.webp'),
  email: require('~/assets/images/ilustrations/Email.webp'),
  emailPng: require('~/assets/images/ilustrations/Email.png'),
  error: require('~/assets/images/ilustrations/Error.webp'),
  estrella: require('~/assets/images/ilustrations/Estrella.webp'),
  exito: require('~/assets/images/ilustrations/Exito.webp'),
  exitoTarjeta: require('~/assets/images/ilustrations/ExitoTarjeta.webp'),
  link: require('~/assets/images/ilustrations/link-dynamic-color.svg'),
  logoInicioDark: require('~/assets/images/ilustrations/LogoInicio Dark.webp'),
  logoInicioLight: require('~/assets/images/ilustrations/LogoInicio Light.webp'),
  maletaConsultor: require('~/assets/images/ilustrations/MaletaConsultor.webp'),
  monedas: require('~/assets/images/ilustrations/Monedas.webp'),
  onBoard1: require('~/assets/images/ilustrations/Onboard-01.webp'),
  onBoard2: require('~/assets/images/ilustrations/Onboard-02.webp'),
  onBoard3: require('~/assets/images/ilustrations/Onboard-03.webp'),
  onBoard4: require('~/assets/images/ilustrations/Onboard-04.webp'),
  referidos: require('~/assets/images/ilustrations/Referidos.webp'),
  noShops: require('~/assets/images/ilustrations/SinComercios.png'),
  saleOk: require('~/assets/images/ilustrations/VentaOK.png'),
  saleKo: require('~/assets/images/ilustrations/VentaKO.png'),
  magictrick: require('~/assets/images/ilustrations/magictrick.png'),
  tienda: require('~/assets/images/ilustrations/Tienda.svg'),
  facebook: require('~/assets/images/social/facebook.svg'),
  instagram: require('~/assets/images/social/instagram.png'),
  mail: require('~/assets/images/social/mail.png'),
  twitter: require('~/assets/images/social/twitter.svg'),
  whatsapp: require('~/assets/images/social/whatsapp.svg'),
  iconRotateRight: require('~/assets/icons/cropper_icons/rotate_right.svg'),
  iconRotateLeft: require('~/assets/icons/cropper_icons/rotate_left.svg'),
  iconFlip: require('~/assets/icons/cropper_icons/flip.svg'),
  balance: require('~/assets/images/ilustrations/fondo_saldo.png'),
  card: require('~/assets/images/ilustrations/card.png'),
  chip: require('~/assets/images/ilustrations/chip.svg'),
  symbol: require('~/assets/images/ilustrations/symbol.svg'),
  telegram: require('~/assets/images/social/telegram.svg'),
  mapIcon: require('~/assets/icons/svg/shopPoint.svg'),
  shopSearch: require('~/assets/images/ilustrations/shopSearch.svg'),
  checklist: require('~/assets/images/ilustrations/checklist.svg'),
  checksearch: require('~/assets/images/ilustrations/checksearch.svg'),
  mapPoint: require('~/assets/images/ilustrations/mapPoint.svg'),
  ready: require('~/assets/images/ilustrations/ready.svg'),
  money: require('~/assets/images/ilustrations/money.png'),
  financial: require('~/assets/images/ilustrations/financial.svg'),
  atraer: require('~/assets/images/ilustrations/atraer.svg'),
  desenfoque: require('~/assets/images/ilustrations/desenfoque.png'),
  banklock: require('~/assets/images/ilustrations/3Dbank.svg'),
  onboardhouse: require('~/assets/images/ilustrations/onboardhouse.svg'),
  onboardcoins: require('~/assets/images/ilustrations/onboardcoins.svg'),
  onboardpiggy: require('~/assets/images/ilustrations/onboardpiggy.svg'),
  onboardhousePlane: require('~/assets/images/ilustrations/onboardhouseplane.svg'),
  onboardwallet: require('~/assets/images/ilustrations/onboardwallet.svg'),
  coheteDinero: require('~/assets/images/ilustrations/coheteDinero.png'),
  maletaDinero: require('~/assets/images/ilustrations/maletaDinero.png'),
  difuminado: require('~/assets/images/ilustrations/difuminado.png'),
  gift: require('~/assets/images/ilustrations/gift.svg'),
  key: require('~/assets/images/ilustrations/key.svg'),
  intersect: require('~/assets/images/ilustrations/intersect.svg'),
  intersectDark: require('~/assets/images/ilustrations/intersectDark.svg'),
  bubble: require('~/assets/images/ilustrations/bubble.svg'),
  bubbleTwo: require('~/assets/images/ilustrations/bubbleTwo.svg'),
  bubbleThree: require('~/assets/images/ilustrations/bubbleThree.svg'),
  bubbleFour: require('~/assets/images/ilustrations/bubbleFour.svg'),
  bubbleFive: require('~/assets/images/ilustrations/bubbleFive.svg'),
  bigBubble: require('~/assets/images/ilustrations/bigBubble.svg'),
}
export default Assets
