apiVersion: v1
kind: Service
metadata:
  namespace: __NAMESPACE__
  name: spa
  labels:
    app: spa
spec:
  type: ClusterIP
  selector:
    app: spa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
